/** @format */

declare module '*.css'
declare module '*.less'
declare module '*.scss'
declare module '*.sass'
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.json'
declare module 'ndarray-resample'
declare module 'ndarray'
declare module 'dsp.js'
